name: Laravel

on:
  push:
    branches: [ "main", "sandbox" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t app .

    - name: Run Docker Container
      run: docker run -d --name cname --network host app

    - name: Install Composer Dependencies
      run: docker exec -t cname composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        docker exec -t cname php artisan key:generate
 
    - name: Execute tests
      run: docker exec -t cname php artisan test

    # - name: Copy .env
    #   run: |
    #     docker exec -t cname cp .env.example .env
    #     # Configurar src/.env para apontar para o serviço MySQL
    #     docker exec -t cname sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env

    # - name: Generate key
    #   run: docker exec -t cname php artisan key:generate

    # - name: Directory Permissions
    #   run: docker exec -t cname chmod -R 777 storage bootstrap/cache

    # - name: Execute PHPUnit tests
    #   run: docker exec -t cname php artisan test
