name: Laravel

on:
  push:
    branches: [ "main", "sandbox" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v3

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d
        docker ps -a

    - name: Install Composer Dependencies
      run: docker-compose exec app composer install --no-scripts
 
    - name: Copy .env
      run: |
        docker exec -t cname cp .env.example .env
        
    - name: Run Migrations
      run: docker-compose exec app php artisan migrate
 
    - name: Execute tests
      run: docker-compose exec app php artisan test
    
