name: Laravel

on:
  push:
    branches: [ "main", "sandbox" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: adorei
          MYSQL_PASSWORD: adoreimesmo
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t app .

    - name: Run Docker Container
      run: docker run -d --name cname --network host app
      # Use '--network host' para que o Laravel acesse o MySQL na mesma rede do host

    - name: Install Composer Dependencies
      run: docker exec -t cname composer install --no-scripts

    - name: Copy .env
      run: |
        docker exec -t cname cp .env.example .env
        # Configurar .env para apontar para o serviço MySQL
        docker exec -t cname sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env

    - name: Generate key
      run: docker exec -t cname php artisan key:generate

    - name: Directory Permissions
      run: docker exec -t cname chmod -R 777 storage bootstrap/cache

    - name: Execute PHPUnit tests
      run: docker exec -t cname php artisan test
